function [fitresult, gof] = LorentzianFit(freq2, p2)
%LorentzianFit(FREQ2,P2)
%  Create a lorentzian fit to data.
%
%  Data for 'Lorentzian' fit:
%      X Input : freq2
%      Y Output: p2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Aug-2013 20:06:35
% 


%% Fit: 'Lorentzian'.
[xData, yData] = prepareCurveData( freq2, p2 );

% Set up fittype and options.
ft = fittype( 'a/(1+b^2*x^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.MaxIter = 10000;
opts.StartPoint = [1 0.000001];
opts.Upper = [Inf Inf];
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'Lorentzian' );
%h = plot( fitresult, xData, yData );
%legend( h, 'p2 vs. freq', 'Lorentzian', 'Location', 'NorthEast' );
% Label axes
%xlabel( 'f' );
%ylabel( 'p^2/p_{max}^2' );
%grid on


