function [trap_x1, trap_y1, pos_x, pos_y, t, z, trap_x2, trap_y2] = read_cv_data_twotraps( filename )
%[trap_x, trap_y, pos_x, pos_y, t, z, trap_x2, trap_y2] = READ_CV_DATA_TWOTRAPS( filename )
% Reads CV data generated by the manual force measurement program
%this  data contains traps 1 and 2 instead of just trap 1.

%% Initialize variables.
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f) = Trap X1, MHz
%	column2: double (%f) = Trap Y1, MHz
%   column3: double (%f) = Trap X2, MHz
%	column4: double (%f) = Trap Y2, MHz
%   column5: double (%f) = Bead_x, V or Nm (if conversion is used);
%	column6: double (%f) = Bead_y, V or Nm (if conversion is used);
%   column7: double (%f) = delta t, time between points, ms
%   column8: double (%f) = z-position, micron
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
trap_x1 = dataArray{:, 1};
trap_y1 = dataArray{:, 2};
trap_x2 = dataArray{:, 3};
trap_y2 = dataArray{:, 4};
pos_x = dataArray{:, 5};
pos_y = dataArray{:, 6};
t = dataArray{:, 7};
z = dataArray{:, 8};

%% find all trailing zeroes due to pre-allocation
valid = find(t > 0);
trap_x1 = trap_x1(valid);
trap_y1 = trap_y1(valid);
trap_x2 = trap_x2(valid);
trap_y2 = trap_y2(valid);
pos_x = pos_x(valid);
pos_y = pos_y(valid);
t = t(valid);
z = z(valid);


