function [rate, d, g, z, Vx,Vy, Nx, Ny] = read_calibration_data(filename)
%READ_CALIBRATION_DATA reads calibration from .dat file generated by the
%Laser Tweezers Interface program (written in LabView). 
%
%
%[rate, d, g, z, Vx,Vy, Nx, Ny] = READ_CALIBATION_DATA(filename)
%returns sampling rate (rate), bead diameter (d), gain (g), z-counts (z), voltage
%readings in x and y directions (Vx,Vy) and number of points in x-y
%readings (i.e. size(Vx), size(Vy)).
%
%see also READ_CV_DATA

fID = fopen(filename);

a = fread(fID,4,'double','b');
rate = a(1);
d = a(2);
g = a(3);
z = a(4);
Nx = fread(fID,1,'int','b');
Vx = fread(fID,Nx,'double','b');
Ny = fread(fID,1,'int','b');
Vy = fread(fID,Ny,'double','b');

fclose(fID);


end

