function [fitresult, gof] = linearFit(t, d)
%CREATEFIT(T,D)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: d
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Jul-2015 17:19:56


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, d );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Lower = [-Inf 0];
opts.Upper = [Inf 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft,opts);

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'd vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel( 't' );
%ylabel( 'd' );
%grid on


