function create_speed_plot(XMatrix1, YMatrix1, LMatrix1, UMatrix1)
%CREATEFIGURE(XMATRIX1, YMATRIX1, LMATRIX1, UMATRIX1)
%  XMATRIX1:  errorbar x matrix
%  YMATRIX1:  errorbar y matrix
%  LMATRIX1:  errorbar l matrix
%  UMATRIX1:  errorbar u matrix

%  Auto-generated by MATLAB on 28-Feb-2016 03:23:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','XScale','log',...
    'FontSize',20,...
    'FontName','Calibri');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[5 1200]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 0.45]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(XMatrix1,YMatrix1,LMatrix1,UMatrix1,'Marker','o',...
    'LineStyle','none');
%set(errorbar1(1),'DisplayName','K365 extension','Visible','off');
%set(errorbar1(2),'DisplayName','K365 buckling','Visible','off');
set(errorbar1(1),'DisplayName','extension','MarkerSize',10,...
    'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'LineWidth',3);
    
set(errorbar1(2),'DisplayName','buckling','MarkerSize',10,...
    'MarkerFaceColor',[0.850980401039124 0.325490206480026 0.0980392172932625],...
    'LineWidth',3);    

% Create xlabel
xlabel('Bulk motor concentration (nM)');

% Create ylabel
ylabel('Speed (\mum s^{-1})');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.610425109095218 0.658033299590554 0.245760566945078 0.205971968312004]);
set(figure1,'Position',[100 100 900 400]);

