%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\f.hilitski\Google Drive\Research\All data compiled (new)\Active MT bundles\extension velocity data.xlsx
%    Worksheet: K401-SA summary
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/02/28 03:10:51

%% Import the data
fpath = 'D:\My Documents\G-Drive\Research\All data compiled (new)\Active MT bundles\extension velocity data.xlsx';
[~, ~, raw] = xlsread(fpath,'K401-SA summary','B43:H49');
%[~, ~, raw] = xlsread('D:\My Documents\G-Drive\Research\All data compiled (new)\Active MT bundles\extension velocity data.xlsx','K356-SA summary','A20:E24');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
c = data(:,1);
buckling_speed = data(:,2);
buckling_error = data(:,3);
extension_speed = data(:,4);
extension_error = data(:,5);
force_measurement = data(:,6);
force_error = data(:,7);

%% Clear temporary variables
clearvars data raw R;