function [c,buckling_speed,buckling_error,extension_speed,extension_error,force_measurement,force_error] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [c,buckling_speed,buckling_error,extension_speed,extension_error,force_measurement,force_error]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [c,buckling_speed,buckling_error,extension_speed,extension_error,force_measurement,force_error]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [c,buckling_speed,buckling_error,extension_speed,extension_error,force_measurement,force_error]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [c,buckling_speed,buckling_error,extension_speed,extension_error,force_measurement,force_error] = importfile('extension velocity data.xlsx','K401-SA summary',43,49);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/02/28 03:10:22

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 43;
    endRow = 49;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('B%d:H%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('B%d:H%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
c = data(:,1);
buckling_speed = data(:,2);
buckling_error = data(:,3);
extension_speed = data(:,4);
extension_error = data(:,5);
force_measurement = data(:,6);
force_error = data(:,7);

